### ISSUE TITLE
include LICENSE with bundled metaschemas

### ISSUE THREAD

**Issue by karenetheridge** [karenetheridge/JSON-Schema-Modern#64]
see https://github.com/json-schema-org/json-schema-spec/issues/1160. The debian-perl folks have expressed concerns about the lack of licence provided for the metaschemas that I'm pulling from the json-schema-spec repository.

**Comment by karenetheridge** [comment]
This is blocked on there being a suitable LICENSE file in the json-schema-spec repository that I can copy alongside all the schema files.

**Comment by gregoa** [comment]
I guess that's resolved with ff35211?

Cheers,
gregor

**Comment by karenetheridge** [comment]
Yes, indeed, version 0.557, 2022-10-30.
