### ISSUE TITLE
Error: Can't locate object method "allow_bignum" via package "JSON::XS"

### ISSUE THREAD

**Issue by full-of-joy** [karenetheridge/JSON-Schema-Modern#69]
I've encountered the following error: 
Can't locate object method "allow_bignum" via package "JSON::XS" at /usr/lib/perl5/vendor_perl/5.26.1/JSON/MaybeXS.pm line 50

Here's a test-script to reproduce it.
I hope it helps.
[Test.zip](https://github.com/karenetheridge/JSON-Schema-Modern/files/8089011/Test.zip)

**Comment by karenetheridge** [comment]
You're using JSON.pm, which is loading JSON::XS, and JSON::XS doesn't support bignums. JSON::MaybeXS provides a much more sane JSON translation layer.

https://metacpan.org/pod/Perl::Critic::Policy::Community::DiscouragedModules#JSON::XS
