### ISSUE TITLE
error parsing schema file with a minimum value for a number

### ISSUE THREAD

**Issue by lschierer** [karenetheridge/JSON-Schema-Modern#86]
given a schema file that has a component that sets a minimum value for something of type number, OpenAPI::Modern will refuse to load it saying "got ambiguous type, not number" on the minimum, then "not all properties are valid" on the object containing it. 
[openapi.yaml.txt](https://github.com/user-attachments/files/17511639/openapi.yaml.txt)

I reduced my actual API file down enough to show the error fairly clearly without lots of extraneous stuff in it.  This API file validates fine with both the SwaggerUI viewer and the ibm-openapi-validator (though it does show some warnings with the latter, it shows no errors).

**Comment by lschierer** [comment]
Changing to YAML::PP did indeed get me past any issue.   Since this seems to be a known bug with the YAML::XS folks, you can close this as it doesn't seem like there's anything for you to do except maybe document a compatibility limitation? 

Thanks for the support!!

**Comment by karenetheridge** [comment]
Resolved in release 0.594, which is more forgiving of malformed numeric strings.
